/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author herod
 */
public class Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(975, 410));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(null);

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jButton1.setText("Voltar");
        jPanel1.add(jButton1);
        jButton1.setBounds(30, 250, 100, 30);

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jButton2.setText("Criar Conta");
        jPanel1.add(jButton2);
        jButton2.setBounds(160, 250, 100, 30);

        jTextField2.setBackground(new java.awt.Color(51, 51, 51));
        jTextField2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(204, 204, 204));
        jTextField2.setText("Email");
        jTextField2.setBorder(null);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(60, 120, 190, 20);

        jPasswordField1.setBackground(new java.awt.Color(51, 51, 51));
        jPasswordField1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(204, 204, 204));
        jPasswordField1.setText("153213.");
        jPasswordField1.setBorder(null);
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(60, 200, 190, 13);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\herod\\OneDrive\\Área de Trabalho\\índice.png")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 220, 200, 2);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\herod\\OneDrive\\Área de Trabalho\\índice.png")); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 140, 200, 2);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\herod\\OneDrive\\Área de Trabalho\\email_blue_23344.png")); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 120, 30, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\herod\\OneDrive\\Área de Trabalho\\icon_senha.png")); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 200, 30, 30);

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Economisa Ja");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 30, 220, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\herod\\OneDrive\\Área de Trabalho\\feltros-lisos-santa-fe-feltro-azul-royal-031--p-1538074880355.jpg")); // NOI18N
        jLabel7.setToolTipText("");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 80, 90, 10);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\herod\\OneDrive\\Área de Trabalho\\icon_senha.png")); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 160, 30, 30);

        jPasswordField2.setBackground(new java.awt.Color(51, 51, 51));
        jPasswordField2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jPasswordField2.setForeground(new java.awt.Color(204, 204, 204));
        jPasswordField2.setText("153213.");
        jPasswordField2.setBorder(null);
        jPanel1.add(jPasswordField2);
        jPasswordField2.setBounds(60, 160, 190, 13);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\herod\\OneDrive\\Área de Trabalho\\índice.png")); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(60, 180, 200, 2);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(120, 30, 290, 300);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\herod\\OneDrive\\Área de Trabalho\\dicas-de-economia-para-ter-mais-dinheiro-no-fim-do-mes.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 960, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
