/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TGI;

import DTO.RegistroDTO;
import conexao.Registros;
import javax.swing.JOptionPane;

/**
 *
 * @author herod
 */
public class TelaNovo extends javax.swing.JFrame {

    /**
     * Creates new form Sistema
     */
    public TelaNovo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FixoMensal = new javax.swing.ButtonGroup();
        DespesaReceita = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtparcelas = new javax.swing.JTextField();
        txtvalor = new javax.swing.JTextField();
        txtnome = new javax.swing.JTextField();
        cbtipo = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        rbfixo = new javax.swing.JRadioButton();
        rbmensal = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        txtdata = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        rbdesp = new javax.swing.JRadioButton();
        rbreceita = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtdesc = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(126, 123, 123));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(38, 38, 38));
        jPanel2.setLayout(null);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Home\\Documents\\NetBeansProjects\\TGI\\fundo-cinza-03.jpg")); // NOI18N
        jPanel2.add(jLabel5);
        jLabel5.setBounds(40, 410, 150, 2);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Home\\Documents\\NetBeansProjects\\TGI\\fundo-cinza-03.jpg")); // NOI18N
        jPanel2.add(jLabel6);
        jLabel6.setBounds(40, 280, 150, 2);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Home\\Documents\\NetBeansProjects\\TGI\\fundo-cinza-03.jpg")); // NOI18N
        jPanel2.add(jLabel7);
        jLabel7.setBounds(40, 150, 150, 2);

        jButton2.setBackground(new java.awt.Color(38, 38, 38));
        jButton2.setFont(new java.awt.Font("Heineken", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 204, 204));
        jButton2.setText("Sair");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(70, 440, 80, 50);

        jButton3.setBackground(new java.awt.Color(38, 38, 38));
        jButton3.setFont(new java.awt.Font("Heineken", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 51));
        jButton3.setText("Novo");
        jButton3.setBorder(null);
        jPanel2.add(jButton3);
        jButton3.setBounds(70, 190, 80, 50);

        jButton4.setBackground(new java.awt.Color(38, 38, 38));
        jButton4.setFont(new java.awt.Font("Heineken", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(204, 204, 204));
        jButton4.setText("Registros");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(70, 320, 80, 50);

        jLabel12.setFont(new java.awt.Font("Heineken", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("ECONOMIZE JA");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(20, 60, 180, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 220, 620);

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel3.setLayout(null);
        jPanel3.add(txtparcelas);
        txtparcelas.setBounds(130, 200, 220, 30);
        jPanel3.add(txtvalor);
        txtvalor.setBounds(130, 120, 220, 30);

        txtnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomeActionPerformed(evt);
            }
        });
        jPanel3.add(txtnome);
        txtnome.setBounds(130, 40, 220, 30);

        cbtipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aluguel", "Conta de água", "Conta de luz", "Conta de telefone", "Conta de celular", "Conta de gás", "Compras", "Escola", "Farmacos ", "Internet", "IPTU", "IPVA", "Médico", "Salário", "Serviço", "Vale", "Venda", "Outros...", " " }));
        cbtipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbtipoActionPerformed(evt);
            }
        });
        jPanel3.add(cbtipo);
        cbtipo.setBounds(130, 80, 220, 30);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Tipo:");
        jPanel3.add(jLabel19);
        jLabel19.setBounds(60, 80, 40, 20);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Data:");
        jPanel3.add(jLabel20);
        jLabel20.setBounds(60, 160, 40, 20);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Nome:");
        jPanel3.add(jLabel21);
        jLabel21.setBounds(50, 40, 50, 20);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Parcelas:");
        jPanel3.add(jLabel22);
        jLabel22.setBounds(40, 200, 60, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Descrição:");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(30, 240, 70, 17);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("Valor:");
        jPanel3.add(jLabel23);
        jLabel23.setBounds(60, 120, 40, 20);

        rbfixo.setBackground(new java.awt.Color(255, 255, 255));
        FixoMensal.add(rbfixo);
        rbfixo.setText("Fixo");
        jPanel3.add(rbfixo);
        rbfixo.setBounds(130, 300, 100, 30);

        rbmensal.setBackground(new java.awt.Color(255, 255, 255));
        FixoMensal.add(rbmensal);
        rbmensal.setText("Mensal");
        jPanel3.add(rbmensal);
        rbmensal.setBounds(240, 300, 100, 30);

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("*opcional");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(40, 260, 50, 14);

        try {
            txtdata.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel3.add(txtdata);
        txtdata.setBounds(130, 160, 220, 30);

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setLayout(null);

        jButton1.setText("Adicionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);
        jButton1.setBounds(290, 10, 90, 30);

        DespesaReceita.add(rbdesp);
        rbdesp.setText("Despesa");
        jPanel4.add(rbdesp);
        rbdesp.setBounds(10, 10, 90, 30);

        DespesaReceita.add(rbreceita);
        rbreceita.setText("Receita");
        jPanel4.add(rbreceita);
        rbreceita.setBounds(110, 10, 90, 30);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(0, 370, 390, 50);

        jScrollPane1.setViewportView(txtdesc);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(130, 240, 220, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Home\\Documents\\NetBeansProjects\\TGI\\fundo-cinza-02.jpg")); // NOI18N
        jPanel3.add(jLabel3);
        jLabel3.setBounds(0, 0, 390, 420);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(420, 70, 390, 420);

        jLabel1.setFont(new java.awt.Font("Base 02", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Home\\Documents\\NetBeansProjects\\TGI\\fundo-azul-escuro-1024x701.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(220, 0, 770, 560);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 984, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String Nome,Tipo,Data,Modo,Descricao,Fixo;
            int Parcelas;
            float Valor; 
    
            Nome = txtnome.getText();
            Tipo = (String) cbtipo.getSelectedItem();
            Valor = Float.parseFloat(txtvalor.getText().replaceAll(",",".")); 
            Data = txtdata.getText();
            Parcelas = Integer.parseInt(txtparcelas.getText());
            Descricao = txtdesc.getText();
            
            
            if (rbdesp.isSelected()== true) {   
             Modo = "Despesa"; 
            }
            else {
             Modo = "Receita"; 
            }
            
            if (rbfixo.isSelected()== true) {  
             Fixo = "Fixo"; 
            }
            else {
             Fixo = "Mensal"; 
            }
            
            
            RegistroDTO objregistro = new RegistroDTO();
            objregistro.setNome(Nome);
            objregistro.setTipo(Tipo);
            objregistro.setValor(Valor);
            objregistro.setData(Data);
            objregistro.setParcelas(Parcelas);
            objregistro.setDescricao(Descricao);
            objregistro.setFixo(Fixo);
            objregistro.setModo(Modo);
                    
            Registros reg = new Registros();
            reg.novoRegistro(objregistro);
            
            txtnome.setText("");
            txtvalor.setText("");
            txtdata.setText("");
            txtparcelas.setText("");
            txtdesc.setText("");
            
            
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, "Erro!!! Preencha todos os corretamente.");
        }
   
            
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbtipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbtipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbtipoActionPerformed

    private void txtnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomeActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       TelaRegistro objregistro = new TelaRegistro();
       objregistro.setVisible(true);
       dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        TelaEntrar objentrar = new TelaEntrar();
        objentrar.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaNovo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaNovo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaNovo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaNovo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaNovo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup DespesaReceita;
    private javax.swing.ButtonGroup FixoMensal;
    private javax.swing.JComboBox<String> cbtipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbdesp;
    private javax.swing.JRadioButton rbfixo;
    private javax.swing.JRadioButton rbmensal;
    private javax.swing.JRadioButton rbreceita;
    private javax.swing.JFormattedTextField txtdata;
    private javax.swing.JTextPane txtdesc;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtparcelas;
    private javax.swing.JTextField txtvalor;
    // End of variables declaration//GEN-END:variables
}
